### ISSUE TITLE
Media url when running Node Red in docker

### ISSUE THREAD

**Issue by hazyitsm** [orcema/node-red-google-notify#11]
I'm running NodeRed as a docker container on an Unraid host. I see in the readme:

> url: optional url if running within docker

I can hear my Google Home respond with the initial beep when I try to run; but the message doesn't play. I get an error in NodeRed: "Failed to load media, check media server in config".

I should also note that the Google Home is running on a separate IoT subnet, while the Node Red host is on my main network.

What should I use as the media server url when running NodeRed in a docker container? Thanks!

**Comment by orcema** [comment]
can you please send some logs if available ?

**Comment by hazyitsm** [comment]
Node-red log when url config is EMPTY. 192.168.xx.xxx is my Google Home. The 172.17.0.x is my Node-red container bridge to the host IP.

```
Queued messages [
{
devicePlaySettings: {
msg: [Object],
sourceNode: [GoogleNotify],
ip: '192.168.xx.xxx',
playVolumeLevel: 0.75,
playMessage: 'This is a test',
language: 'en',
speakSlow: false,
mediaServerUrl: 'http://172.17.0.x',
mediaServerPort: '8098',
cacheFolder: '/tmp'
},
callback: [Function (anonymous)]
}
]
setting up mediaPlayUrl
preparing socket for connection to device
connecting with device
preparing player on device
preparing to stop any playing media
inital vol level {
controlType: 'master',
level: 0.44999998807907104,
muted: false,
stepInterval: 0.019999999552965164
} device 192.168.xx.xxx
Vol level set to 0.75 device 192.168.xx.xxx
preparing to play media
mediaPlayUrl: http://172.17.0.x:8098/THIS_IS_A_TEST-en-normal.mp3
status broadcast currentPlayerState=IDLE for host 192.168.xx.xxx
status broadcast currentPlayerState=BUFFERING for host 192.168.xx.xxx
media http://172.17.0.x:8098/THIS_IS_A_TEST-en-normal.mp3 not available Error: Load failed

at /data/node_modules/castv2-client/lib/controllers/media.js:75:23
at fn.onmessage (/data/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
at fn.emit (events.js:412:35)
at Channel.onmessage (/data/node_modules/castv2-client/lib/controllers/controller.js:16:10)

at Channel.emit (events.js:400:28)
at Client.onmessage (/data/node_modules/castv2/lib/channel.js:23:10)
at Client.emit (events.js:412:35)
at PacketStreamWrapper.onpacket (/data/node_modules/castv2/lib/client.js:81:10)
at PacketStreamWrapper.emit (events.js:400:28)
at TLSSocket.<anonymous> (/data/node_modules/castv2/lib/packet-stream-wrapper.js:28:16)
status broadcast currentPlayerState=IDLE for host 192.168.xx.xxx #
```

**Comment by hazyitsm** [comment]
I think I figured it out. If I change the Node-red container network type to use HOST instead of BRIDGE, it worked as expected.

**Comment by orcema** [comment]
fine, happy you spotted the issue
